### ISSUE TITLE
InternalCompilerError: undefined method `compatible?' for nil:NilClass

### ISSUE THREAD

**Issue by abscondment** [mirah/mirah#157]
Updating my project to 0.0.10 from 0.0.9 showed a new compilation snag:

```
Mirah::InternalCompilerError: undefined method `compatible?' for nil:NilClass
         infer at /Users/brendan/code/mirah/lib/mirah/typer/simple.rb:280
         infer at /Users/brendan/code/mirah/lib/mirah/ast/flow.rb:376
    resolve_if at /Users/brendan/code/mirah/lib/mirah/ast.rb:248
         infer at /Users/brendan/code/mirah/lib/mirah/ast/flow.rb:374
         infer at /Users/brendan/code/mirah/lib/mirah/typer/simple.rb:275
         infer at /Users/brendan/code/mirah/lib/mirah/ast/structure.rb:34
          each at org/jruby/RubyArray.java:1614
```

Git bisect between 0.0.9 and 0.0.10 pins it on 677e4aa29d

I don't quite grok what's going on here, but I have a test case to help in fixing things: https://gist.github.com/1478479
